import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: {
    default: 'SITENAME',
    template: '%s | SITENAME'
  },
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'lightsteelblue',
            padding: '40px',
            marginBottom: '20px'
          }}
        >
          Header
        </header>
        <main
          style={{
            backgroundColor: 'lightcoral',
            padding: '40px',
            marginBottom: '20px'
          }}
        >
          {children}
        </main>
        <footer
          style={{
            backgroundColor: 'lightseagreen',
            padding: '40px'
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  )
}
